Add new im-launch command and change hook script

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,8 +4,14 @@
 
 set -e
 
-# acb685ae9264be3fc1800f98a70b12bb  80im-switch.1.14
-# 044a2f13aa8382902dc8f47dc7da7064  80im-switch.1.16
+# version just before wheezy release
+# acb685ae9264be3fc1800f98a70b12bb  80im-switch 1.14
+# 044a2f13aa8382902dc8f47dc7da7064  80im-switch 1.16 (oldstable) - 1.22 (unstable)
+
+# 4045a8eeb0e9226cdd9f8a121ccf4c04  80im-config_launch 0.3 (stable initial)
+# 8a4829f935b5561ca6e61bec6eb3893f  80im-config_launch 0.3+squeeze1 (stable), 0.4
+# b243876a16f7b87c397ceef626098069  80im-config_launch 0.5
+# 5ef27261ac38d704d8f766da19635461  80im-config_launch 0.6-0.17 (testing, unstable)
 
 case "$1" in
     configure)
@@ -19,6 +25,19 @@ case "$1" in
     
                 *)
                     echo "ERROR: Unknown hook file exists: $IM_SWITCH_HOOK." >&2
+                ;;
+            esac
+        fi
+        IM_CONFIG_HOOK=/etc/X11/Xsession.d/80im-config_launch
+        if [ -f $IM_CONFIG_HOOK ]; then
+            IM_CONFIG_HOOK_MD5SUM=$(md5sum < $IM_CONFIG_HOOK|cut -d ' ' -f 1)
+            case $IM_CONFIG_HOOK_MD5SUM in
+                4045a8eeb0e9226cdd9f8a121ccf4c04|8a4829f935b5561ca6e61bec6eb3893f|b243876a16f7b87c397ceef626098069|5ef27261ac38d704d8f766da19635461)
+                    rm -f $IM_CONFIG_HOOK
+                ;;
+    
+                *)
+                    echo "ERROR: Unknown hook file exists: $IM_CONFIG_HOOK." >&2
                 ;;
             esac
         fi
